ef_connect:
    path:  /efconnect/{instance}
    defaults: { _controller: FMElfinderBundle:ElFinder:load, instance: default }
elfinder:
    path: /elfinder/{instance}
    defaults: { _controller: FMElfinderBundle:ElFinder:show, instance: default }
