language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false 

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=2.7.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev

before_install:
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script: phpunit --coverage-clover=clover.xml

after_script:
  - php vendor/bin/coveralls -v
  
notifications:
  email: helios.ag@gmail.com
